"""Add cascade delete constraints

Revision ID: 5305a7e4231a
Revises: ca8b1bcbdac2
Create Date: 2026-06-28 04:10:48.608921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5305a7e4231a'
down_revision: Union[str, Sequence[str], None] = 'ca8b1bcbdac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interviewanswer_session_id_fkey'), 'interviewanswer', type_='foreignkey')
    op.create_foreign_key(None, 'interviewanswer', 'jobsession', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('jobsession_user_id_fkey'), 'jobsession', type_='foreignkey')
    op.create_foreign_key(None, 'jobsession', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rankingresult_session_id_fkey'), 'rankingresult', type_='foreignkey')
    op.create_foreign_key(None, 'rankingresult', 'jobsession', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rankingresult', type_='foreignkey')
    op.create_foreign_key(op.f('rankingresult_session_id_fkey'), 'rankingresult', 'jobsession', ['session_id'], ['id'])
    op.drop_constraint(None, 'jobsession', type_='foreignkey')
    op.create_foreign_key(op.f('jobsession_user_id_fkey'), 'jobsession', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'interviewanswer', type_='foreignkey')
    op.create_foreign_key(op.f('interviewanswer_session_id_fkey'), 'interviewanswer', 'jobsession', ['session_id'], ['id'])
    # ### end Alembic commands ###
